name: Build Intel Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      ARCHFLAGS: "-arch x86_64"
      SYSTEM_VERSION_COMPAT: "1"
      MACOSX_DEPLOYMENT_TARGET: "10.13"
    steps:
      - uses: actions/checkout@v4
      
      - name: Check macOS version and architecture
        run: |
          sw_vers
          uname -a
          arch
          if [ "$(arch)" = "arm64" ]; then
            echo "Error: This workflow requires Intel architecture"
            exit 1
          fi
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      
      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            python -m pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
            pip list
          
      - name: Check system info
        run: |
          python --version
          echo "Current directory: $PWD"
          ls -la
          echo "MACOSX_DEPLOYMENT_TARGET: $MACOSX_DEPLOYMENT_TARGET"
          
      - name: Build app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            echo "Starting PyInstaller build..."
            python -m PyInstaller --version
            python -m PyInstaller \
              --clean \
              --noconfirm \
              --name ImageToPDF \
              --windowed \
              --target-arch x86_64 \
              --distpath ./dist \
              --workpath ./build \
              --osx-bundle-identifier "com.doudoudoufff.imagetopdf" \
              main.py
          
      - name: Check build output
        run: |
          echo "Checking build output..."
          ls -la dist/
          otool -L dist/ImageToPDF.app/Contents/MacOS/ImageToPDF || true
          
      - name: Package app
        run: |
          echo "Creating zip archive..."
          cd dist
          ls -la
          if [ -d "ImageToPDF.app" ]; then
            # 设置应用程序的最低系统要求
            /usr/libexec/PlistBuddy -c "Set :LSMinimumSystemVersion 10.13" ImageToPDF.app/Contents/Info.plist
            zip -r ImageToPDF-Intel-Mac.zip ImageToPDF.app
            echo "Zip file created successfully"
          else
            echo "Error: ImageToPDF.app directory not found"
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageToPDF-Intel-Mac
          path: dist/ImageToPDF-Intel-Mac.zip
          
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ImageToPDF-Intel-Mac.zip
          name: Intel Mac Release
          tag_name: v${{ github.run_number }}
          generate_release_notes: true 