name: Build Intel Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-13
    timeout-minutes: 30
    env:
      ARCHFLAGS: "-arch x86_64"
      SYSTEM_VERSION_COMPAT: "1"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          arch -x86_64 /bin/bash -c "
            python -m pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
            pip install 'PyInstaller==6.5.0'
          "

      - name: Replace bootloader with x86_64-only version
        run: |
          arch -x86_64 /bin/bash -c "
            # 下载并解压 x86_64 bootloader
            curl -L -o bootloader.tar.gz https://github.com/pyinstaller/pyinstaller/releases/download/v6.5.0/pyinstaller-bootloader-darwin-x86_64.tar.gz
            tar -xzvf bootloader.tar.gz
            
            # 获取 PyInstaller bootloader 目录
            BOOTLOADER_DIR=\$(python -c 'import PyInstaller; print(PyInstaller.__path__[0])')/bootloader/Darwin-64bit
            
            # 备份原始 bootloader
            mv \"\$BOOTLOADER_DIR\" \"\${BOOTLOADER_DIR}.bak\" || true
            mkdir -p \"\$BOOTLOADER_DIR\"
            
            # 复制新的 bootloader
            cp darwin-x86_64/* \"\$BOOTLOADER_DIR/\"
            
            # 检查替换结果
            ls -la \"\$BOOTLOADER_DIR\"
            file \"\$BOOTLOADER_DIR/runw\"
          "
          
      - name: Check system info
        run: |
          arch -x86_64 /bin/bash -c "
            python --version
            echo 'Current directory: $PWD'
            ls -la
            echo 'MACOSX_DEPLOYMENT_TARGET: $MACOSX_DEPLOYMENT_TARGET'
            pip list
          "
          
      - name: Build app
        run: |
          arch -x86_64 /bin/bash -c "
            echo 'Starting PyInstaller build...'
            python -m PyInstaller \
              --clean \
              --noconfirm \
              --name ImageToPDF \
              --windowed \
              --distpath ./dist \
              --workpath ./build \
              --osx-bundle-identifier 'com.doudoudoufff.imagetopdf' \
              main.py
          "
          
      - name: Check build output
        run: |
          echo "Checking build output..."
          ls -la dist/
          arch -x86_64 /bin/bash -c "otool -L dist/ImageToPDF.app/Contents/MacOS/ImageToPDF" || true
          
      - name: Package app
        run: |
          echo "Creating zip archive..."
          cd dist
          ls -la
          if [ -d "ImageToPDF.app" ]; then
            # 设置应用程序的最低系统要求
            /usr/libexec/PlistBuddy -c "Set :LSMinimumSystemVersion 13.0" ImageToPDF.app/Contents/Info.plist
            zip -r ImageToPDF-Intel-Mac.zip ImageToPDF.app
            echo "Zip file created successfully"
          else
            echo "Error: ImageToPDF.app directory not found"
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageToPDF-Intel-Mac
          path: dist/ImageToPDF-Intel-Mac.zip
          
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ImageToPDF-Intel-Mac.zip
          name: Intel Mac Release
          tag_name: v${{ github.run_number }}
          generate_release_notes: true 