name: Build Intel Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build app
        run: |
          pyinstaller --clean --noconfirm --name ImageToPDF \
            --add-data "README.md:." \
            --windowed \
            --target-arch x86_64 \
            --distpath ./dist \
            --workpath ./build \
            main.py
      
      - name: Package app
        run: |
          cd dist
          zip -r ImageToPDF-Intel-Mac.zip ImageToPDF.app
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageToPDF-Intel-Mac
          path: dist/ImageToPDF-Intel-Mac.zip
          
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ImageToPDF-Intel-Mac.zip
          name: Intel Mac Release
          tag_name: v${{ github.run_number }}
          generate_release_notes: true 