name: Build Intel Mac App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list
          
      - name: Check system info
        run: |
          python --version
          arch
          uname -a
          echo "Current directory: $PWD"
          ls -la
      
      - name: Build app
        run: |
          echo "Starting PyInstaller build..."
          python -m PyInstaller --version
          python -m PyInstaller \
            --clean \
            --noconfirm \
            --name ImageToPDF \
            --windowed \
            --target-arch x86_64 \
            --distpath ./dist \
            --workpath ./build \
            --debug all \
            main.py
          
      - name: Check build output
        run: |
          echo "Checking build output..."
          ls -la dist/
          
      - name: Package app
        run: |
          echo "Creating zip archive..."
          cd dist
          ls -la
          if [ -d "ImageToPDF.app" ]; then
            zip -r ImageToPDF-Intel-Mac.zip ImageToPDF.app
            echo "Zip file created successfully"
          else
            echo "Error: ImageToPDF.app directory not found"
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageToPDF-Intel-Mac
          path: dist/ImageToPDF-Intel-Mac.zip
          
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ImageToPDF-Intel-Mac.zip
          name: Intel Mac Release
          tag_name: v${{ github.run_number }}
          generate_release_notes: true 